version: '2.3'

services:

  app:
    build: .
    container_name: app
    image: alyleite/laravel
    volumes:
      - /e/docker:/var/www # docker toolbox
#      -  .:/var/www # docker desktop
    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - /e/docker:/var/www # docker toolbox
#      -  .:/var/www # docker desktop
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - /e/docker/.docker/dbdata:/var/lib/mysql # docker toolbox
#      -  ./.docker/dbdata:/var/lib/mysql # docker desktop
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 4

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
